<?php

/**
 * @file
 * Cavalla_embed_media module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function cavalla_embed_media_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.cavalla_embed_media':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 * Lets us define our paragraphs templates in this module.
 */
function cavalla_embed_media_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__cavalla_embed_media' => [
      'base hook' => 'paragraph',
    ],

    'paragraph__cavalla_embed_media_soundcloud' => [
      'base hook' => 'paragraph',
    ],

    'paragraph__cavalla_embed_media_youtube' => [
      'base hook' => 'paragraph',
    ],

  ];
}

/**
 *
 */
function cavalla_embed_media_preprocess_paragraph__cavalla_embed_media_youtube(&$variables) {
  $paragraph = $variables['elements']['#paragraph'];
  $variables['url'] = str_replace('https://youtu.be/', 'https://www.youtube.com/embed/', $paragraph->get('field_cavalla_em_youtube')->value);
}
