<?php

/**
 * @file
 * cavalla_commerce install file.
 */

/**
 *
 */
function cavalla_commerce_update_8001() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'cavalla_commerce');
}

function cavalla_commerce_update_8002() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'cavalla_commerce');
}

function cavalla_commerce_update_8003() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'cavalla_commerce');
}
