<?php

/**
 * @file
 */

/**
 *
 */
function cavalla_taxonomy_update_8001() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'cavalla_taxonomy');
}

function cavalla_taxonomy_update_8002() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'cavalla_taxonomy');
}

function cavalla_taxonomy_update_8003() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'cavalla_taxonomy');
}

