<?php

/**
 * @file
 * Cavalla_featurette module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function cavalla_featurette_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.cavalla_featurette':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 * Lets us define our paragraphs templates in this module.
 */
function cavalla_featurette_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__cavalla_featurette' => [
      'base hook' => 'paragraph',
    ],

  ];
}

/**
 *
 */
function cavalla_featurette_preprocess_paragraph__cavalla_featurette(array &$variables) {
  $paragraph = $variables['elements']['#paragraph'];
  $variables['float_left'] = $paragraph->get('field_featurette_image_alignment')->value;
  $circular_image = $paragraph->get('field_cavalla_featurette_cimg')->value;

  if ($circular_image == 1) {
    $variables['circular_image'] = 'circular_image';
  }
}
